import Tablet from "@/components/Tablet";

interface Tablet {
  Tablet_Number: string;
  Block: string;
  Row_Number: string;
  Column_Number: string;
  Status: string;
}


const tabletArray: Tablet[] = 
[{
  "Tablet_Number": "C0101",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "01",
  "Status": "Available"
}, {
  "Tablet_Number": "C0103",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "03",
  "Status": "Available"
}, {
  "Tablet_Number": "C0105",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "05",
  "Status": "Available"
}, {
  "Tablet_Number": "C0107",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "07",
  "Status": "Available"
}, {
  "Tablet_Number": "C0109",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "09",
  "Status": "Available"
}, {
  "Tablet_Number": "C0111",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "11",
  "Status": "Available"
}, {
  "Tablet_Number": "C0113",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "13",
  "Status": "Available"
}, {
  "Tablet_Number": "C0115",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "15",
  "Status": "Available"
}, {
  "Tablet_Number": "C0117",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "17",
  "Status": "Available"
}, {
  "Tablet_Number": "C0119",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "19",
  "Status": "Available"
}, {
  "Tablet_Number": "C0121",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "21",
  "Status": "Available"
}, {
  "Tablet_Number": "C0123",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "23",
  "Status": "Available"
}, {
  "Tablet_Number": "C0125",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "25",
  "Status": "Available"
}, {
  "Tablet_Number": "C0127",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "27",
  "Status": "Available"
}, {
  "Tablet_Number": "C0129",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "29",
  "Status": "Available"
}, {
  "Tablet_Number": "C0131",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "31",
  "Status": "Available"
}, {
  "Tablet_Number": "C0133",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "33",
  "Status": "Available"
}, {
  "Tablet_Number": "C0135",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "35",
  "Status": "Available"
}, {
  "Tablet_Number": "C0137",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "37",
  "Status": "Available"
}, {
  "Tablet_Number": "C0139",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "39",
  "Status": "Available"
}, {
  "Tablet_Number": "C0141",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "41",
  "Status": "Available"
}, {
  "Tablet_Number": "C0143",
  "Block": "C",
  "Row_Number": "01",
  "Column_Number": "43",
  "Status": "Available"
}, {
  "Tablet_Number": "C0202",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "02",
  "Status": "Available"
}, {
  "Tablet_Number": "C0204",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "04",
  "Status": "Available"
}, {
  "Tablet_Number": "C0206",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "06",
  "Status": "Available"
}, {
  "Tablet_Number": "C0208",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "08",
  "Status": "Available"
}, {
  "Tablet_Number": "C0210",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "10",
  "Status": "Available"
}, {
  "Tablet_Number": "C0212",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "12",
  "Status": "Available"
}, {
  "Tablet_Number": "C0214",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "14",
  "Status": "Available"
}, {
  "Tablet_Number": "C0216",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "16",
  "Status": "Available"
}, {
  "Tablet_Number": "C0218",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "18",
  "Status": "Available"
}, {
  "Tablet_Number": "C0220",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "20",
  "Status": "Available"
}, {
  "Tablet_Number": "C0222",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "22",
  "Status": "Available"
}, {
  "Tablet_Number": "C0224",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "24",
  "Status": "Available"
}, {
  "Tablet_Number": "C0226",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "26",
  "Status": "Available"
}, {
  "Tablet_Number": "C0228",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "28",
  "Status": "Available"
}, {
  "Tablet_Number": "C0230",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "30",
  "Status": "Available"
}, {
  "Tablet_Number": "C0232",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "32",
  "Status": "Available"
}, {
  "Tablet_Number": "C0234",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "34",
  "Status": "Available"
}, {
  "Tablet_Number": "C0236",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "36",
  "Status": "Available"
}, {
  "Tablet_Number": "C0238",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "38",
  "Status": "Available"
}, {
  "Tablet_Number": "C0240",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "40",
  "Status": "Available"
}, {
  "Tablet_Number": "C0242",
  "Block": "C",
  "Row_Number": "02",
  "Column_Number": "42",
  "Status": "Available"
}, {
  "Tablet_Number": "C0301",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "01",
  "Status": "Available"
}, {
  "Tablet_Number": "C0303",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "03",
  "Status": "Available"
}, {
  "Tablet_Number": "C0305",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "05",
  "Status": "Available"
}, {
  "Tablet_Number": "C0307",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "07",
  "Status": "Available"
}, {
  "Tablet_Number": "C0309",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "09",
  "Status": "Available"
}, {
  "Tablet_Number": "C0311",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "11",
  "Status": "Available"
}, {
  "Tablet_Number": "C0313",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "13",
  "Status": "Available"
}, {
  "Tablet_Number": "C0315",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "15",
  "Status": "Available"
}, {
  "Tablet_Number": "C0317",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "17",
  "Status": "Available"
}, {
  "Tablet_Number": "C0319",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "19",
  "Status": "Available"
}, {
  "Tablet_Number": "C0321",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "21",
  "Status": "Available"
}, {
  "Tablet_Number": "C0323",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "23",
  "Status": "Available"
}, {
  "Tablet_Number": "C0325",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "25",
  "Status": "Available"
}, {
  "Tablet_Number": "C0327",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "27",
  "Status": "Available"
}, {
  "Tablet_Number": "C0329",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "29",
  "Status": "Available"
}, {
  "Tablet_Number": "C0331",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "31",
  "Status": "Available"
}, {
  "Tablet_Number": "C0333",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "33",
  "Status": "Available"
}, {
  "Tablet_Number": "C0335",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "35",
  "Status": "Available"
}, {
  "Tablet_Number": "C0337",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "37",
  "Status": "Available"
}, {
  "Tablet_Number": "C0339",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "39",
  "Status": "Available"
}, {
  "Tablet_Number": "C0341",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "41",
  "Status": "Available"
}, {
  "Tablet_Number": "C0343",
  "Block": "C",
  "Row_Number": "03",
  "Column_Number": "43",
  "Status": "Available"
}, {
  "Tablet_Number": "C0402",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "02",
  "Status": "Available"
}, {
  "Tablet_Number": "C0404",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "04",
  "Status": "Available"
}, {
  "Tablet_Number": "C0406",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "06",
  "Status": "Available"
}, {
  "Tablet_Number": "C0408",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "08",
  "Status": "Available"
}, {
  "Tablet_Number": "C0410",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "10",
  "Status": "Available"
}, {
  "Tablet_Number": "C0412",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "12",
  "Status": "Available"
}, {
  "Tablet_Number": "C0414",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "14",
  "Status": "Available"
}, {
  "Tablet_Number": "C0416",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "16",
  "Status": "Available"
}, {
  "Tablet_Number": "C0418",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "18",
  "Status": "Available"
}, {
  "Tablet_Number": "C0420",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "20",
  "Status": "Available"
}, {
  "Tablet_Number": "C0422",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "22",
  "Status": "Available"
}, {
  "Tablet_Number": "C0424",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "24",
  "Status": "Available"
}, {
  "Tablet_Number": "C0426",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "26",
  "Status": "Available"
}, {
  "Tablet_Number": "C0428",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "28",
  "Status": "Available"
}, {
  "Tablet_Number": "C0430",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "30",
  "Status": "Available"
}, {
  "Tablet_Number": "C0432",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "32",
  "Status": "Available"
}, {
  "Tablet_Number": "C0434",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "34",
  "Status": "Available"
}, {
  "Tablet_Number": "C0436",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "36",
  "Status": "Available"
}, {
  "Tablet_Number": "C0438",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "38",
  "Status": "Available"
}, {
  "Tablet_Number": "C0440",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "40",
  "Status": "Available"
}, {
  "Tablet_Number": "C0442",
  "Block": "C",
  "Row_Number": "04",
  "Column_Number": "42",
  "Status": "Available"
}, {
  "Tablet_Number": "C0501",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "01",
  "Status": "Available"
}, {
  "Tablet_Number": "C0503",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "03",
  "Status": "Available"
}, {
  "Tablet_Number": "C0505",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "05",
  "Status": "Available"
}, {
  "Tablet_Number": "C0507",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "07",
  "Status": "Available"
}, {
  "Tablet_Number": "C0509",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "09",
  "Status": "Available"
}, {
  "Tablet_Number": "C0511",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "11",
  "Status": "Available"
}, {
  "Tablet_Number": "C0513",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "13",
  "Status": "Available"
}, {
  "Tablet_Number": "C0515",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "15",
  "Status": "Available"
}, {
  "Tablet_Number": "C0517",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "17",
  "Status": "Available"
}, {
  "Tablet_Number": "C0519",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "19",
  "Status": "Available"
}, {
  "Tablet_Number": "C0521",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "21",
  "Status": "Available"
}, {
  "Tablet_Number": "C0523",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "23",
  "Status": "Available"
}, {
  "Tablet_Number": "C0525",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "25",
  "Status": "Available"
}, {
  "Tablet_Number": "C0527",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "27",
  "Status": "Available"
}, {
  "Tablet_Number": "C0529",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "29",
  "Status": "Available"
}, {
  "Tablet_Number": "C0531",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "31",
  "Status": "Available"
}, {
  "Tablet_Number": "C0533",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "33",
  "Status": "Available"
}, {
  "Tablet_Number": "C0535",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "35",
  "Status": "Available"
}, {
  "Tablet_Number": "C0537",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "37",
  "Status": "Available"
}, {
  "Tablet_Number": "C0539",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "39",
  "Status": "Available"
}, {
  "Tablet_Number": "C0541",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "41",
  "Status": "Available"
}, {
  "Tablet_Number": "C0543",
  "Block": "C",
  "Row_Number": "05",
  "Column_Number": "43",
  "Status": "Available"
}, {
  "Tablet_Number": "C0602",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "02",
  "Status": "Available"
}, {
  "Tablet_Number": "C0604",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "04",
  "Status": "Available"
}, {
  "Tablet_Number": "C0606",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "06",
  "Status": "Available"
}, {
  "Tablet_Number": "C0608",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "08",
  "Status": "Available"
}, {
  "Tablet_Number": "C0610",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "10",
  "Status": "Available"
}, {
  "Tablet_Number": "C0612",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "12",
  "Status": "Available"
}, {
  "Tablet_Number": "C0614",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "14",
  "Status": "Available"
}, {
  "Tablet_Number": "C0616",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "16",
  "Status": "Available"
}, {
  "Tablet_Number": "C0618",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "18",
  "Status": "Available"
}, {
  "Tablet_Number": "C0620",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "20",
  "Status": "Available"
}, {
  "Tablet_Number": "C0622",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "22",
  "Status": "Available"
}, {
  "Tablet_Number": "C0624",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "24",
  "Status": "Available"
}, {
  "Tablet_Number": "C0626",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "26",
  "Status": "Available"
}, {
  "Tablet_Number": "C0628",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "28",
  "Status": "Available"
}, {
  "Tablet_Number": "C0630",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "30",
  "Status": "Available"
}, {
  "Tablet_Number": "C0632",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "32",
  "Status": "Available"
}, {
  "Tablet_Number": "C0634",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "34",
  "Status": "Available"
}, {
  "Tablet_Number": "C0636",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "36",
  "Status": "Available"
}, {
  "Tablet_Number": "C0638",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "38",
  "Status": "Available"
}, {
  "Tablet_Number": "C0640",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "40",
  "Status": "Available"
}, {
  "Tablet_Number": "C0642",
  "Block": "C",
  "Row_Number": "06",
  "Column_Number": "42",
  "Status": "Available"
}, {
  "Tablet_Number": "C0701",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "01",
  "Status": "Available"
}, {
  "Tablet_Number": "C0703",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "03",
  "Status": "Available"
}, {
  "Tablet_Number": "C0705",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "05",
  "Status": "Available"
}, {
  "Tablet_Number": "C0707",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "07",
  "Status": "Available"
}, {
  "Tablet_Number": "C0709",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "09",
  "Status": "Available"
}, {
  "Tablet_Number": "C0711",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "11",
  "Status": "Available"
}, {
  "Tablet_Number": "C0713",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "13",
  "Status": "Available"
}, {
  "Tablet_Number": "C0715",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "15",
  "Status": "Available"
}, {
  "Tablet_Number": "C0717",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "17",
  "Status": "Available"
}, {
  "Tablet_Number": "C0719",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "19",
  "Status": "Available"
}, {
  "Tablet_Number": "C0721",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "21",
  "Status": "Available"
}, {
  "Tablet_Number": "C0723",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "23",
  "Status": "Available"
}, {
  "Tablet_Number": "C0725",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "25",
  "Status": "Available"
}, {
  "Tablet_Number": "C0727",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "27",
  "Status": "Available"
}, {
  "Tablet_Number": "C0729",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "29",
  "Status": "Available"
}, {
  "Tablet_Number": "C0731",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "31",
  "Status": "Available"
}, {
  "Tablet_Number": "C0733",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "33",
  "Status": "Available"
}, {
  "Tablet_Number": "C0735",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "35",
  "Status": "Available"
}, {
  "Tablet_Number": "C0737",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "37",
  "Status": "Available"
}, {
  "Tablet_Number": "C0739",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "39",
  "Status": "Available"
}, {
  "Tablet_Number": "C0741",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "41",
  "Status": "Available"
}, {
  "Tablet_Number": "C0743",
  "Block": "C",
  "Row_Number": "07",
  "Column_Number": "43",
  "Status": "Available"
}, {
  "Tablet_Number": "C0802",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "02",
  "Status": "Available"
}, {
  "Tablet_Number": "C0804",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "04",
  "Status": "Available"
}, {
  "Tablet_Number": "C0806",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "06",
  "Status": "Available"
}, {
  "Tablet_Number": "C0808",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "08",
  "Status": "Available"
}, {
  "Tablet_Number": "C0810",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "10",
  "Status": "Available"
}, {
  "Tablet_Number": "C0812",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "12",
  "Status": "Available"
}, {
  "Tablet_Number": "C0814",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "14",
  "Status": "Available"
}, {
  "Tablet_Number": "C0816",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "16",
  "Status": "Available"
}, {
  "Tablet_Number": "C0818",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "18",
  "Status": "Available"
}, {
  "Tablet_Number": "C0820",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "20",
  "Status": "Available"
}, {
  "Tablet_Number": "C0822",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "22",
  "Status": "Available"
}, {
  "Tablet_Number": "C0824",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "24",
  "Status": "Available"
}, {
  "Tablet_Number": "C0826",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "26",
  "Status": "Available"
}, {
  "Tablet_Number": "C0828",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "28",
  "Status": "Available"
}, {
  "Tablet_Number": "C0830",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "30",
  "Status": "Available"
}, {
  "Tablet_Number": "C0832",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "32",
  "Status": "Available"
}, {
  "Tablet_Number": "C0834",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "34",
  "Status": "Available"
}, {
  "Tablet_Number": "C0836",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "36",
  "Status": "Available"
}, {
  "Tablet_Number": "C0838",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "38",
  "Status": "Available"
}, {
  "Tablet_Number": "C0840",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "40",
  "Status": "Available"
}, {
  "Tablet_Number": "C0842",
  "Block": "C",
  "Row_Number": "08",
  "Column_Number": "42",
  "Status": "Available"
}, {
  "Tablet_Number": "C0901",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "01",
  "Status": "Available"
}, {
  "Tablet_Number": "C0903",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "03",
  "Status": "Available"
}, {
  "Tablet_Number": "C0905",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "05",
  "Status": "Available"
}, {
  "Tablet_Number": "C0907",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "07",
  "Status": "Available"
}, {
  "Tablet_Number": "C0909",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "09",
  "Status": "Available"
}, {
  "Tablet_Number": "C0911",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "11",
  "Status": "Available"
}, {
  "Tablet_Number": "C0913",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "13",
  "Status": "Available"
}, {
  "Tablet_Number": "C0915",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "15",
  "Status": "Available"
}, {
  "Tablet_Number": "C0917",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "17",
  "Status": "Available"
}, {
  "Tablet_Number": "C0919",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "19",
  "Status": "Available"
}, {
  "Tablet_Number": "C0921",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "21",
  "Status": "Available"
}, {
  "Tablet_Number": "C0923",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "23",
  "Status": "Available"
}, {
  "Tablet_Number": "C0925",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "25",
  "Status": "Available"
}, {
  "Tablet_Number": "C0927",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "27",
  "Status": "Available"
}, {
  "Tablet_Number": "C0929",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "29",
  "Status": "Available"
}, {
  "Tablet_Number": "C0931",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "31",
  "Status": "Available"
}, {
  "Tablet_Number": "C0933",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "33",
  "Status": "Available"
}, {
  "Tablet_Number": "C0935",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "35",
  "Status": "Available"
}, {
  "Tablet_Number": "C0937",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "37",
  "Status": "Available"
}, {
  "Tablet_Number": "C0939",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "39",
  "Status": "Available"
}, {
  "Tablet_Number": "C0941",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "41",
  "Status": "Available"
}, {
  "Tablet_Number": "C0943",
  "Block": "C",
  "Row_Number": "09",
  "Column_Number": "43",
  "Status": "Available"
}, {
  "Tablet_Number": "C1002",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "02",
  "Status": "Available"
}, {
  "Tablet_Number": "C1004",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "04",
  "Status": "Available"
}, {
  "Tablet_Number": "C1006",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "06",
  "Status": "Available"
}, {
  "Tablet_Number": "C1008",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "08",
  "Status": "Available"
}, {
  "Tablet_Number": "C1010",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "10",
  "Status": "Available"
}, {
  "Tablet_Number": "C1012",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "12",
  "Status": "Available"
}, {
  "Tablet_Number": "C1014",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "14",
  "Status": "Available"
}, {
  "Tablet_Number": "C1016",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "16",
  "Status": "Available"
}, {
  "Tablet_Number": "C1018",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "18",
  "Status": "Available"
}, {
  "Tablet_Number": "C1020",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "20",
  "Status": "Available"
}, {
  "Tablet_Number": "C1022",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "22",
  "Status": "Available"
}, {
  "Tablet_Number": "C1024",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "24",
  "Status": "Available"
}, {
  "Tablet_Number": "C1026",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "26",
  "Status": "Available"
}, {
  "Tablet_Number": "C1028",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "28",
  "Status": "Available"
}, {
  "Tablet_Number": "C1030",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "30",
  "Status": "Available"
}, {
  "Tablet_Number": "C1032",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "32",
  "Status": "Available"
}, {
  "Tablet_Number": "C1034",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "34",
  "Status": "Available"
}, {
  "Tablet_Number": "C1036",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "36",
  "Status": "Available"
}, {
  "Tablet_Number": "C1038",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "38",
  "Status": "Available"
}, {
  "Tablet_Number": "C1040",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "40",
  "Status": "Available"
}, {
  "Tablet_Number": "C1042",
  "Block": "C",
  "Row_Number": "10",
  "Column_Number": "42",
  "Status": "Available"
}, {
  "Tablet_Number": "C1101",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "01",
  "Status": "Available"
}, {
  "Tablet_Number": "C1103",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "03",
  "Status": "Available"
}, {
  "Tablet_Number": "C1105",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "05",
  "Status": "Available"
}, {
  "Tablet_Number": "C1107",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "07",
  "Status": "Available"
}, {
  "Tablet_Number": "C1109",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "09",
  "Status": "Available"
}, {
  "Tablet_Number": "C1111",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "11",
  "Status": "Available"
}, {
  "Tablet_Number": "C1113",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "13",
  "Status": "Available"
}, {
  "Tablet_Number": "C1115",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "15",
  "Status": "Available"
}, {
  "Tablet_Number": "C1117",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "17",
  "Status": "Available"
}, {
  "Tablet_Number": "C1119",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "19",
  "Status": "Available"
}, {
  "Tablet_Number": "C1121",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "21",
  "Status": "Available"
}, {
  "Tablet_Number": "C1123",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "23",
  "Status": "Available"
}, {
  "Tablet_Number": "C1125",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "25",
  "Status": "Available"
}, {
  "Tablet_Number": "C1127",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "27",
  "Status": "Available"
}, {
  "Tablet_Number": "C1129",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "29",
  "Status": "Available"
}, {
  "Tablet_Number": "C1131",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "31",
  "Status": "Available"
}, {
  "Tablet_Number": "C1133",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "33",
  "Status": "Available"
}, {
  "Tablet_Number": "C1135",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "35",
  "Status": "Available"
}, {
  "Tablet_Number": "C1137",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "37",
  "Status": "Available"
}, {
  "Tablet_Number": "C1139",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "39",
  "Status": "Available"
}, {
  "Tablet_Number": "C1141",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "41",
  "Status": "Available"
}, {
  "Tablet_Number": "C1143",
  "Block": "C",
  "Row_Number": "11",
  "Column_Number": "43",
  "Status": "Available"
}, {
  "Tablet_Number": "C1202",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "02",
  "Status": "Available"
}, {
  "Tablet_Number": "C1204",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "04",
  "Status": "Available"
}, {
  "Tablet_Number": "C1206",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "06",
  "Status": "Available"
}, {
  "Tablet_Number": "C1208",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "08",
  "Status": "Available"
}, {
  "Tablet_Number": "C1210",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "10",
  "Status": "Available"
}, {
  "Tablet_Number": "C1212",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "12",
  "Status": "Available"
}, {
  "Tablet_Number": "C1214",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "14",
  "Status": "Available"
}, {
  "Tablet_Number": "C1216",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "16",
  "Status": "Available"
}, {
  "Tablet_Number": "C1218",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "18",
  "Status": "Available"
}, {
  "Tablet_Number": "C1220",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "20",
  "Status": "Available"
}, {
  "Tablet_Number": "C1222",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "22",
  "Status": "Available"
}, {
  "Tablet_Number": "C1224",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "24",
  "Status": "Available"
}, {
  "Tablet_Number": "C1226",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "26",
  "Status": "Available"
}, {
  "Tablet_Number": "C1228",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "28",
  "Status": "Available"
}, {
  "Tablet_Number": "C1230",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "30",
  "Status": "Available"
}, {
  "Tablet_Number": "C1232",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "32",
  "Status": "Available"
}, {
  "Tablet_Number": "C1234",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "34",
  "Status": "Available"
}, {
  "Tablet_Number": "C1236",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "36",
  "Status": "Available"
}, {
  "Tablet_Number": "C1238",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "38",
  "Status": "Available"
}, {
  "Tablet_Number": "C1240",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "40",
  "Status": "Available"
}, {
  "Tablet_Number": "C1242",
  "Block": "C",
  "Row_Number": "12",
  "Column_Number": "42",
  "Status": "Available"
}, {
  "Tablet_Number": "C1301",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "01",
  "Status": "Available"
}, {
  "Tablet_Number": "C1303",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "03",
  "Status": "Available"
}, {
  "Tablet_Number": "C1305",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "05",
  "Status": "Available"
}, {
  "Tablet_Number": "C1307",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "07",
  "Status": "Available"
}, {
  "Tablet_Number": "C1309",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "09",
  "Status": "Available"
}, {
  "Tablet_Number": "C1311",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "11",
  "Status": "Available"
}, {
  "Tablet_Number": "C1313",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "13",
  "Status": "Available"
}, {
  "Tablet_Number": "C1315",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "15",
  "Status": "Available"
}, {
  "Tablet_Number": "C1317",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "17",
  "Status": "Available"
}, {
  "Tablet_Number": "C1319",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "19",
  "Status": "Available"
}, {
  "Tablet_Number": "C1321",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "21",
  "Status": "Available"
}, {
  "Tablet_Number": "C1323",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "23",
  "Status": "Available"
}, {
  "Tablet_Number": "C1325",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "25",
  "Status": "Available"
}, {
  "Tablet_Number": "C1327",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "27",
  "Status": "Available"
}, {
  "Tablet_Number": "C1329",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "29",
  "Status": "Available"
}, {
  "Tablet_Number": "C1331",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "31",
  "Status": "Available"
}, {
  "Tablet_Number": "C1333",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "33",
  "Status": "Available"
}, {
  "Tablet_Number": "C1335",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "35",
  "Status": "Available"
}, {
  "Tablet_Number": "C1337",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "37",
  "Status": "Available"
}, {
  "Tablet_Number": "C1339",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "39",
  "Status": "Available"
}, {
  "Tablet_Number": "C1341",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "41",
  "Status": "Available"
}, {
  "Tablet_Number": "C1343",
  "Block": "C",
  "Row_Number": "13",
  "Column_Number": "43",
  "Status": "Available"
}, {
  "Tablet_Number": "C1402",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "02",
  "Status": "Available"
}, {
  "Tablet_Number": "C1404",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "04",
  "Status": "Available"
}, {
  "Tablet_Number": "C1406",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "06",
  "Status": "Available"
}, {
  "Tablet_Number": "C1408",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "08",
  "Status": "Available"
}, {
  "Tablet_Number": "C1410",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "10",
  "Status": "Available"
}, {
  "Tablet_Number": "C1412",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "12",
  "Status": "Available"
}, {
  "Tablet_Number": "C1414",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "14",
  "Status": "Available"
}, {
  "Tablet_Number": "C1416",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "16",
  "Status": "Available"
}, {
  "Tablet_Number": "C1418",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "18",
  "Status": "Available"
}, {
  "Tablet_Number": "C1420",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "20",
  "Status": "Available"
}, {
  "Tablet_Number": "C1422",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "22",
  "Status": "Available"
}, {
  "Tablet_Number": "C1424",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "24",
  "Status": "Available"
}, {
  "Tablet_Number": "C1426",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "26",
  "Status": "Available"
}, {
  "Tablet_Number": "C1428",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "28",
  "Status": "Available"
}, {
  "Tablet_Number": "C1430",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "30",
  "Status": "Available"
}, {
  "Tablet_Number": "C1432",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "32",
  "Status": "Available"
}, {
  "Tablet_Number": "C1434",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "34",
  "Status": "Available"
}, {
  "Tablet_Number": "C1436",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "36",
  "Status": "Available"
}, {
  "Tablet_Number": "C1438",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "38",
  "Status": "Available"
}, {
  "Tablet_Number": "C1440",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "40",
  "Status": "Available"
}, {
  "Tablet_Number": "C1442",
  "Block": "C",
  "Row_Number": "14",
  "Column_Number": "42",
  "Status": "Available"
}, {
  "Tablet_Number": "C1501",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "01",
  "Status": "Available"
}, {
  "Tablet_Number": "C1503",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "03",
  "Status": "Available"
}, {
  "Tablet_Number": "C1505",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "05",
  "Status": "Available"
}, {
  "Tablet_Number": "C1507",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "07",
  "Status": "Available"
}, {
  "Tablet_Number": "C1509",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "09",
  "Status": "Available"
}, {
  "Tablet_Number": "C1511",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "11",
  "Status": "Available"
}, {
  "Tablet_Number": "C1513",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "13",
  "Status": "Available"
}, {
  "Tablet_Number": "C1515",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "15",
  "Status": "Available"
}, {
  "Tablet_Number": "C1517",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "17",
  "Status": "Available"
}, {
  "Tablet_Number": "C1519",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "19",
  "Status": "Available"
}, {
  "Tablet_Number": "C1521",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "21",
  "Status": "Available"
}, {
  "Tablet_Number": "C1523",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "23",
  "Status": "Available"
}, {
  "Tablet_Number": "C1525",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "25",
  "Status": "Available"
}, {
  "Tablet_Number": "C1527",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "27",
  "Status": "Available"
}, {
  "Tablet_Number": "C1529",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "29",
  "Status": "Available"
}, {
  "Tablet_Number": "C1531",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "31",
  "Status": "Available"
}, {
  "Tablet_Number": "C1533",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "33",
  "Status": "Available"
}, {
  "Tablet_Number": "C1535",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "35",
  "Status": "Available"
}, {
  "Tablet_Number": "C1537",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "37",
  "Status": "Available"
}, {
  "Tablet_Number": "C1539",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "39",
  "Status": "Available"
}, {
  "Tablet_Number": "C1541",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "41",
  "Status": "Available"
}, {
  "Tablet_Number": "C1543",
  "Block": "C",
  "Row_Number": "15",
  "Column_Number": "43",
  "Status": "Available"
}, {
  "Tablet_Number": "C1602",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "02",
  "Status": "Available"
}, {
  "Tablet_Number": "C1604",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "04",
  "Status": "Available"
}, {
  "Tablet_Number": "C1606",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "06",
  "Status": "Available"
}, {
  "Tablet_Number": "C1608",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "08",
  "Status": "Available"
}, {
  "Tablet_Number": "C1610",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "10",
  "Status": "Available"
}, {
  "Tablet_Number": "C1612",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "12",
  "Status": "Available"
}, {
  "Tablet_Number": "C1614",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "14",
  "Status": "Available"
}, {
  "Tablet_Number": "C1616",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "16",
  "Status": "Available"
}, {
  "Tablet_Number": "C1618",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "18",
  "Status": "Available"
}, {
  "Tablet_Number": "C1620",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "20",
  "Status": "Available"
}, {
  "Tablet_Number": "C1622",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "22",
  "Status": "Available"
}, {
  "Tablet_Number": "C1624",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "24",
  "Status": "Available"
}, {
  "Tablet_Number": "C1626",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "26",
  "Status": "Available"
}, {
  "Tablet_Number": "C1628",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "28",
  "Status": "Available"
}, {
  "Tablet_Number": "C1630",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "30",
  "Status": "Available"
}, {
  "Tablet_Number": "C1632",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "32",
  "Status": "Available"
}, {
  "Tablet_Number": "C1634",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "34",
  "Status": "Available"
}, {
  "Tablet_Number": "C1636",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "36",
  "Status": "Available"
}, {
  "Tablet_Number": "C1638",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "38",
  "Status": "Available"
}, {
  "Tablet_Number": "C1640",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "40",
  "Status": "Available"
}, {
  "Tablet_Number": "C1642",
  "Block": "C",
  "Row_Number": "16",
  "Column_Number": "42",
  "Status": "Available"
}, {
  "Tablet_Number": "C1701",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "01",
  "Status": "Available"
}, {
  "Tablet_Number": "C1703",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "03",
  "Status": "Available"
}, {
  "Tablet_Number": "C1705",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "05",
  "Status": "Available"
}, {
  "Tablet_Number": "C1707",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "07",
  "Status": "Available"
}, {
  "Tablet_Number": "C1709",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "09",
  "Status": "Available"
}, {
  "Tablet_Number": "C1711",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "11",
  "Status": "Available"
}, {
  "Tablet_Number": "C1713",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "13",
  "Status": "Available"
}, {
  "Tablet_Number": "C1715",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "15",
  "Status": "Available"
}, {
  "Tablet_Number": "C1717",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "17",
  "Status": "Available"
}, {
  "Tablet_Number": "C1719",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "19",
  "Status": "Available"
}, {
  "Tablet_Number": "C1721",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "21",
  "Status": "Available"
}, {
  "Tablet_Number": "C1723",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "23",
  "Status": "Available"
}, {
  "Tablet_Number": "C1725",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "25",
  "Status": "Available"
}, {
  "Tablet_Number": "C1727",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "27",
  "Status": "Available"
}, {
  "Tablet_Number": "C1729",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "29",
  "Status": "Available"
}, {
  "Tablet_Number": "C1731",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "31",
  "Status": "Available"
}, {
  "Tablet_Number": "C1733",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "33",
  "Status": "Available"
}, {
  "Tablet_Number": "C1735",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "35",
  "Status": "Available"
}, {
  "Tablet_Number": "C1737",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "37",
  "Status": "Available"
}, {
  "Tablet_Number": "C1739",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "39",
  "Status": "Available"
}, {
  "Tablet_Number": "C1741",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "41",
  "Status": "Available"
}, {
  "Tablet_Number": "C1743",
  "Block": "C",
  "Row_Number": "17",
  "Column_Number": "43",
  "Status": "Available"
}] ;


// Sort the array
const sortedTablets = tabletArray.sort((a, b) => {
  // Sort by Row_Number in descending order
  const rowComparison = parseInt(b.Row_Number) - parseInt(a.Row_Number);
  
  // If Row_Numbers are equal, sort by Column_Number in ascending order
  const columnComparison = parseInt(a.Column_Number) - parseInt(b.Column_Number);

  return rowComparison || columnComparison;
});

export default function TabletsMapViewBlockC() {
  return (
    <div className="w-full h-screen overflow-auto">
      <div className="flex flex-col w-max">
        {(() => {
          let blkRowNumber: string
          let currentRow: string | null = null;
          const rows: JSX.Element[] = [];
          let rowItems: JSX.Element[] = []; // Initialize as an empty array
          tabletArray.forEach((tablet, index) => {
            blkRowNumber = tablet.Block + " " +tablet.Row_Number;
            if (currentRow === null || parseInt(tablet.Row_Number) !== parseInt(currentRow)) {
              if (rowItems.length > 0) {
                rows.push(<div className="flex flex-row ">{rowItems}</div>);
                rowItems = [];
              }
              rowItems.push(<h1 className="sticky left-0 pt-5 font-bold flex-none w-10 bg-white">{blkRowNumber}</h1>);
              currentRow = tablet.Row_Number;
            }
            rowItems.push(<Tablet key={tablet.Tablet_Number} block={tablet.Block} row={parseInt(tablet.Row_Number)} number={parseInt(tablet.Column_Number)} status={tablet.Status} />);
            if (index === tabletArray.length - 1) {
              rows.push(<div className="flex flex-row">{rowItems}</div>);
            }
          });
          return rows;
        })()}
      </div>
    </div>
  )
}
