import Tablet from "@/components/Tablet";

interface Tablet {
  Tablet_Number: string;
  Block: string;
  Row_Number: string;
  Column_Number: string;
  Status: string;
}


const tabletArray: Tablet[] = 
  [{
    "Tablet_Number": "B0101",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "01",
    "Status": "ipt in progress"
  }, {
    "Tablet_Number": "B0103",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "03",
    "Status": "reserved"
  }, {
    "Tablet_Number": "B0105",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "05",
    "Status": "occupied"
  }, {
    "Tablet_Number": "B0107",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "07",
    "Status": "blocked"
  }, {
    "Tablet_Number": "B0109",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "09",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0111",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "11",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0113",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "13",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0115",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "15",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0117",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "17",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0119",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "19",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0121",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "21",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0123",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "23",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0125",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "25",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0127",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "27",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0129",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "29",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0131",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "31",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0133",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "33",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0135",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "35",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0137",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "37",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0139",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "39",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0141",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "41",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0143",
    "Block": "B",
    "Row_Number": "01",
    "Column_Number": "43",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0202",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "02",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0204",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "04",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0206",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "06",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0208",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "08",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0210",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "10",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0212",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "12",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0214",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "14",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0216",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "16",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0218",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "18",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0220",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "20",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0222",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "22",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0224",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "24",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0226",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "26",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0228",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "28",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0230",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "30",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0232",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "32",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0234",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "34",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0236",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "36",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0238",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "38",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0240",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "40",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0242",
    "Block": "B",
    "Row_Number": "02",
    "Column_Number": "42",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0301",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "01",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0303",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "03",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0305",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "05",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0307",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "07",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0309",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "09",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0311",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "11",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0313",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "13",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0315",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "15",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0317",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "17",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0319",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "19",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0321",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "21",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0323",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "23",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0325",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "25",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0327",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "27",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0329",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "29",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0331",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "31",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0333",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "33",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0335",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "35",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0337",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "37",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0339",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "39",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0341",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "41",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0343",
    "Block": "B",
    "Row_Number": "03",
    "Column_Number": "43",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0402",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "02",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0404",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "04",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0406",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "06",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0408",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "08",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0410",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "10",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0412",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "12",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0414",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "14",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0416",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "16",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0418",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "18",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0420",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "20",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0422",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "22",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0424",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "24",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0426",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "26",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0428",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "28",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0430",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "30",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0432",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "32",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0434",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "34",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0436",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "36",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0438",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "38",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0440",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "40",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0442",
    "Block": "B",
    "Row_Number": "04",
    "Column_Number": "42",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0501",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "01",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0503",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "03",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0505",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "05",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0507",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "07",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0509",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "09",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0511",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "11",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0513",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "13",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0515",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "15",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0517",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "17",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0519",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "19",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0521",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "21",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0523",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "23",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0525",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "25",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0527",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "27",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0529",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "29",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0531",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "31",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0533",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "33",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0535",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "35",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0537",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "37",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0539",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "39",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0541",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "41",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0543",
    "Block": "B",
    "Row_Number": "05",
    "Column_Number": "43",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0602",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "02",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0604",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "04",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0606",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "06",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0608",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "08",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0610",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "10",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0612",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "12",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0614",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "14",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0616",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "16",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0618",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "18",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0620",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "20",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0622",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "22",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0624",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "24",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0626",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "26",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0628",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "28",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0630",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "30",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0632",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "32",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0634",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "34",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0636",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "36",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0638",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "38",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0640",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "40",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0642",
    "Block": "B",
    "Row_Number": "06",
    "Column_Number": "42",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0701",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "01",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0703",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "03",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0705",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "05",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0707",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "07",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0709",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "09",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0711",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "11",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0713",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "13",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0715",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "15",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0717",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "17",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0719",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "19",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0721",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "21",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0723",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "23",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0725",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "25",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0727",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "27",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0729",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "29",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0731",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "31",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0733",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "33",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0735",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "35",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0737",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "37",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0739",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "39",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0741",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "41",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0743",
    "Block": "B",
    "Row_Number": "07",
    "Column_Number": "43",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0802",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "02",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0804",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "04",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0806",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "06",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0808",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "08",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0810",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "10",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0812",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "12",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0814",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "14",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0816",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "16",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0818",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "18",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0820",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "20",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0822",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "22",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0824",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "24",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0826",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "26",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0828",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "28",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0830",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "30",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0832",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "32",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0834",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "34",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0836",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "36",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0838",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "38",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0840",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "40",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0842",
    "Block": "B",
    "Row_Number": "08",
    "Column_Number": "42",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0901",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "01",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0903",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "03",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0905",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "05",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0907",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "07",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0909",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "09",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0911",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "11",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0913",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "13",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0915",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "15",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0917",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "17",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0919",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "19",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0921",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "21",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0923",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "23",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0925",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "25",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0927",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "27",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0929",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "29",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0931",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "31",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0933",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "33",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0935",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "35",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0937",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "37",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0939",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "39",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0941",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "41",
    "Status": "Available"
  }, {
    "Tablet_Number": "B0943",
    "Block": "B",
    "Row_Number": "09",
    "Column_Number": "43",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1002",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "02",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1004",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "04",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1006",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "06",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1008",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "08",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1010",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "10",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1012",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "12",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1014",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "14",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1016",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "16",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1018",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "18",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1020",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "20",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1022",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "22",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1024",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "24",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1026",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "26",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1028",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "28",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1030",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "30",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1032",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "32",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1034",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "34",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1036",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "36",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1038",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "38",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1040",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "40",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1042",
    "Block": "B",
    "Row_Number": "10",
    "Column_Number": "42",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1101",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "01",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1103",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "03",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1105",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "05",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1107",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "07",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1109",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "09",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1111",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "11",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1113",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "13",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1115",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "15",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1117",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "17",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1119",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "19",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1121",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "21",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1123",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "23",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1125",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "25",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1127",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "27",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1129",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "29",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1131",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "31",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1133",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "33",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1135",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "35",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1137",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "37",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1139",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "39",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1141",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "41",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1143",
    "Block": "B",
    "Row_Number": "11",
    "Column_Number": "43",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1202",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "02",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1204",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "04",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1206",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "06",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1208",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "08",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1210",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "10",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1212",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "12",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1214",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "14",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1216",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "16",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1218",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "18",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1220",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "20",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1222",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "22",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1224",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "24",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1226",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "26",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1228",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "28",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1230",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "30",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1232",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "32",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1234",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "34",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1236",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "36",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1238",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "38",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1240",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "40",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1242",
    "Block": "B",
    "Row_Number": "12",
    "Column_Number": "42",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1301",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "01",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1303",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "03",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1305",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "05",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1307",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "07",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1309",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "09",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1311",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "11",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1313",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "13",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1315",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "15",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1317",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "17",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1319",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "19",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1321",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "21",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1323",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "23",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1325",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "25",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1327",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "27",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1329",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "29",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1331",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "31",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1333",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "33",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1335",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "35",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1337",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "37",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1339",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "39",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1341",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "41",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1343",
    "Block": "B",
    "Row_Number": "13",
    "Column_Number": "43",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1402",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "02",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1404",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "04",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1406",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "06",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1408",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "08",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1410",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "10",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1412",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "12",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1414",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "14",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1416",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "16",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1418",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "18",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1420",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "20",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1422",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "22",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1424",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "24",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1426",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "26",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1428",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "28",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1430",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "30",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1432",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "32",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1434",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "34",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1436",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "36",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1438",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "38",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1440",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "40",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1442",
    "Block": "B",
    "Row_Number": "14",
    "Column_Number": "42",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1501",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "01",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1503",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "03",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1505",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "05",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1507",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "07",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1509",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "09",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1511",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "11",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1513",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "13",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1515",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "15",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1517",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "17",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1519",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "19",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1521",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "21",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1523",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "23",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1525",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "25",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1527",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "27",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1529",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "29",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1531",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "31",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1533",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "33",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1535",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "35",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1537",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "37",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1539",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "39",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1541",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "41",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1543",
    "Block": "B",
    "Row_Number": "15",
    "Column_Number": "43",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1602",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "02",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1604",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "04",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1606",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "06",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1608",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "08",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1610",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "10",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1612",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "12",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1614",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "14",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1616",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "16",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1618",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "18",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1620",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "20",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1622",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "22",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1624",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "24",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1626",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "26",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1628",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "28",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1630",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "30",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1632",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "32",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1634",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "34",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1636",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "36",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1638",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "38",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1640",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "40",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1642",
    "Block": "B",
    "Row_Number": "16",
    "Column_Number": "42",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1701",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "01",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1703",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "03",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1705",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "05",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1707",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "07",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1709",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "09",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1711",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "11",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1713",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "13",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1715",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "15",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1717",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "17",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1719",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "19",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1721",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "21",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1723",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "23",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1725",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "25",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1727",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "27",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1729",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "29",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1731",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "31",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1733",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "33",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1735",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "35",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1737",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "37",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1739",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "39",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1741",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "41",
    "Status": "Available"
  }, {
    "Tablet_Number": "B1743",
    "Block": "B",
    "Row_Number": "17",
    "Column_Number": "43",
    "Status": "Available"
  }] 
;


// Sort the array
const sortedTablets = tabletArray.sort((a, b) => {
  // Sort by Row_Number in descending order
  const rowComparison = parseInt(b.Row_Number) - parseInt(a.Row_Number);
  
  // If Row_Numbers are equal, sort by Column_Number in ascending order
  const columnComparison = parseInt(a.Column_Number) - parseInt(b.Column_Number);

  return rowComparison || columnComparison;
});

export default function TabletsMapViewBlockB() {
  return (
    <div className="w-full h-screen overflow-auto">
      <div className="flex flex-col w-max">
        {(() => {
          let blkRowNumber: string
          let currentRow: string | null = null;
          const rows: JSX.Element[] = [];
          let rowItems: JSX.Element[] = []; // Initialize as an empty array
          tabletArray.forEach((tablet, index) => {
            blkRowNumber = tablet.Block + " " +tablet.Row_Number;
            if (currentRow === null || parseInt(tablet.Row_Number) !== parseInt(currentRow)) {
              if (rowItems.length > 0) {
                rows.push(<div className="flex flex-row ">{rowItems}</div>);
                rowItems = [];
              }
              rowItems.push(<h1 className="sticky left-0 pt-5 font-bold flex-none w-10 bg-white">{blkRowNumber}</h1>);
              currentRow = tablet.Row_Number;
            }
            rowItems.push(<Tablet key={tablet.Tablet_Number} block={tablet.Block} row={parseInt(tablet.Row_Number)} number={parseInt(tablet.Column_Number)} status={tablet.Status} />);
            if (index === tabletArray.length - 1) {
              rows.push(<div className="flex flex-row">{rowItems}</div>);
            }
          });
          return rows;
        })()}
      </div>
    </div>
  )
}
